-- Pure conversion logic from the mason-registry package format to this
-- plugin's registry. Only used by scripts/generate-registry.lua and tests;
-- never loaded at editor runtime.
local M = {}

local function url_decode(s)
	return (s:gsub("%%(%x%x)", function(hex)
		return string.char(tonumber(hex, 16))
	end))
end

---Parse a mason source id (purl), e.g. "pkg:npm/%40angular/language-server@22.0.7".
---@param id string
---@return string? type
---@return string? name
function M.parse_purl(id)
	local typ, rest = id:match("^pkg:([^/]+)/(.+)$")
	if not typ then
		return nil
	end
	rest = rest:gsub("%?.*$", "")
	local name = rest:match("^(.*)@") -- scoped npm "@" is %40-encoded, so a raw "@" only precedes the version
	if not name or name == "" then
		return nil
	end
	return typ, url_decode(name)
end

---Index `mise registry` output: lowercased backend spec -> shortname.
---@param text string
---@return table<string, string>
function M.parse_mise_registry(text)
	local index = {}
	for line in text:gmatch("[^\n]+") do
		local iter = line:gmatch("%S+")
		local name = iter()
		for backend in iter do
			index[backend:lower()] = name
		end
	end
	return index
end

local BACKEND_BY_TYPE = { npm = "npm", pypi = "pipx", cargo = "cargo", golang = "go", gem = "gem" }

---Convert one mason package into a registry entry.
---@param pkg table decoded package from mason's registry.json
---@param mise_index table<string, string> from parse_mise_registry()
---@return string? lspconfig_name
---@return { tool: string, bin: string[] }? entry
function M.convert(pkg, mise_index)
	local lsp = vim.tbl_get(pkg, "neovim", "lspconfig")
	if type(lsp) ~= "string" then
		return nil
	end
	local bins = type(pkg.bin) == "table" and vim.tbl_keys(pkg.bin) or {}
	if #bins == 0 then
		return nil
	end
	table.sort(bins)

	local typ, name = M.parse_purl(pkg.source.id)
	if not typ then
		return nil
	end
	local tool
	if BACKEND_BY_TYPE[typ] then
		tool = BACKEND_BY_TYPE[typ] .. ":" .. name
	elseif typ == "github" then
		-- Prefer curated mise shortnames (mason lowercases repo names, so
		-- match case-insensitively); fall back to ubi for prebuilt assets.
		for _, prefix in ipairs({ "aqua:", "ubi:", "github:", "asdf:" }) do
			tool = mise_index[(prefix .. name):lower()]
			if tool then
				break
			end
		end
		if not tool and pkg.source.asset ~= nil then
			tool = "ubi:" .. name
		end
	end
	if not tool then
		return nil
	end
	tool = mise_index[tool:lower()] or tool
	return lsp, { tool = tool, bin = bins }
end

---Build the full registry keyed by lspconfig server name.
---@param mason_packages table[] decoded mason registry.json
---@param mise_registry_text string output of `mise registry`
---@return table<string, { tool: string?, bin: string[] }>
function M.build(mason_packages, mise_registry_text)
	local index = M.parse_mise_registry(mise_registry_text)
	local registry = {}
	for _, pkg in ipairs(mason_packages) do
		local lsp, entry = M.convert(pkg, index)
		if lsp and not registry[lsp] then
			registry[lsp] = entry
		end
	end
	return registry
end

-- Servers whose cmd is a generic interpreter would match unrelated binaries
-- on $PATH, so they are never added from nvim-lspconfig definitions.
local INTERPRETERS = {
	bash = true,
	bun = true,
	bunx = true,
	java = true,
	node = true,
	npx = true,
	perl = true,
	python = true,
	python3 = true,
	ruby = true,
	sh = true,
}

---Add servers that nvim-lspconfig defines but mason-registry does not cover,
---as bin-only entries (no mise install spec is derivable for them).
---@param registry table<string, { tool: string?, bin: string[] }>
---@param lspconfig_bins table<string, string> lspconfig server name -> cmd[1]
---@return table<string, { tool: string?, bin: string[] }>
function M.augment(registry, lspconfig_bins)
	for name, bin in pairs(lspconfig_bins) do
		if not registry[name] and not INTERPRETERS[bin] then
			registry[name] = { bin = { bin } }
		end
	end
	return registry
end

---Serialize a registry to Lua source with a stable key order.
---@param registry table<string, { tool: string?, bin: string[] }>
---@return string
function M.serialize(registry)
	local keys = vim.tbl_keys(registry)
	table.sort(keys)
	local lines = {
		"-- Generated by scripts/generate-registry.lua from mason-registry data.",
		"-- Do not edit by hand; run the script (or the update-registry workflow).",
		"return {",
	}
	for _, key in ipairs(keys) do
		local entry = registry[key]
		local bins = {}
		for _, bin in ipairs(entry.bin) do
			table.insert(bins, string.format("%q", bin))
		end
		local tool = entry.tool and string.format("tool = %q, ", entry.tool) or ""
		table.insert(lines, string.format("\t[%q] = { %sbin = { %s } },", key, tool, table.concat(bins, ", ")))
	end
	table.insert(lines, "}")
	return table.concat(lines, "\n") .. "\n"
end

return M
