---
on: [push, pull_request]
name: default

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua scripts tests
  selene:
    name: selene
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.31.0
          args: lua scripts tests
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: rhysd/action-setup-vim@v1.6.1
        with:
          neovim: true
          version: stable
      - run: nvim -l tests/run.lua
